name: Deploy to Production

on:
  push:
    branches: [ "dev", "staging", "main" ]
    
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy over SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts

            if [ "${{ github.ref_name }}" == "dev" ]; then
              ssh-keyscan dev.aijoborbit.com >> ~/.ssh/known_hosts
              cd /home/efinder24/dev.aijoborbit.com
              git reset --hard
              git clean -fd
              git pull https://${{ secrets.GH_TOKEN }}@github.com/Cognativeitsolution/jobportal-mvp.git dev
            elif [ "${{ github.ref_name }}" == "staging" ]; then
              ssh-keyscan staging.aijoborbit.com >> ~/.ssh/known_hosts
              cd /home/efinder24/staging.aijoborbit.com
              git reset --hard
              git clean -fd
              git pull https://${{ secrets.GH_TOKEN }}@github.com/Cognativeitsolution/jobportal-mvp.git staging
            elif [ "${{ github.ref_name }}" == "main" ]; then
              ssh-keyscan aijoborbit.com >> ~/.ssh/known_hosts
              cd /home/efinder24/aijoborbit.com
              git reset --hard
              git clean -fd
              git pull https://${{ secrets.GH_TOKEN }}@github.com/Cognativeitsolution/jobportal-mvp.git main
            fi

      - name: Discord Notification
        if: always()
        uses: Ilshidur/action-discord@master
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: |
            ${{ job.status == 'success' && '✅' || '🚨' }} Deployment to **${{ github.ref_name }}** environment done.
            - Commit: ${{ github.event.head_commit.message }}
            - By: ${{ github.actor }}
                                                                                                               